name: Create Windows Executable

on:
  release:
    types: [created]
  
  
jobs:
  windows:
    runs-on: windows-latest
    name: Windows
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: "x64"
      - name: Install PyInstaller
        run: |
          pip3 install pyinstaller
      - name: Get tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Create Executable binary
        run: |
          pyinstaller --onefile just-a-DFC.py
          cd dist
          mv just-a-DFC just-a-DFC-${{ steps.vars.outputs.tag }}.exe
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: just-a-DFC-${{ steps.vars.outputs.tag }}.exe
          name: windows
