name: Make distribution binaries

on:
  push:
    branches: ["*"]
    paths-ignore:
      - README.md
  release:
    types: [created]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install pyinstaller
        run: |
          pip3 install pyinstaller
      - name: Make binary
        run: |
          pyinstaller --onefile just-a-DFC.py
          cd dist
          zip ../just-a-DFC.Linux-amd64.zip just-a-DFC
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          path: just-a-DFC.Linux-amd64.zip
          name: linux

  macos:
    runs-on: macos-latest
    name: macOS
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install pyinstaller
        run: |
          pip3 install pyinstaller
      - name: Make binary
        run: |
          pyinstaller --onefile just-a-DFC.py
          cd dist
          zip ../just-a-DFC.macOS.zip just-a-DFC
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          path: just-a-DFC.macOS.zip
          name: macos

  win32:
    runs-on: ubuntu-latest
    name: Windows
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x86'
      - name: Install pyinstaller
        run: |
          pip3 install pyinstaller
      - name: Make binary
        run: |
          pyinstaller --onefile just-a-DFC.py
          cd dist
          zip ../just-a-DFC.Win32.zip just-a-DFC.exe
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          path: just-a-DFC.Win32.zip
          name: win32

win64:
    runs-on: ubuntu-latest
    name: Windows
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x86'
      - name: Install pyinstaller
        run: |
          pip3 install pyinstaller
      - name: Make binary
        run: |
          pyinstaller --onefile just-a-DFC.py
          cd dist
          zip ../just-a-DFC.Win64.zip just-a-DFC.exe
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          path: just-a-DFC.Win64.zip
          name: win64
